modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
[[mods]]
modId = "rsrequestify"
version = "${file.jarVersion}"
displayName = "RSRequestify"
authors = "Buuz135"
description = "Display your achievements with style"

[[dependencies.rsrequestify]]
    modId="refinedstorage"
    mandatory=true
versionRange = "[1.12.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rsrequestify]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"