modLoader = "javafml"
loaderVersion = "[28,)"
license = "MIT"
[[mods]]
modId = "rsrequestify"
version = "${file.jarVersion}"
displayName = "RSRequestify"
authors = "Buuz135"
description = "Display your achievements with style"
